server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: любой путь отдаёт index.html, маршрутизация на стороне React Router
    location / {
        try_files $uri $uri/ /index.html;
    }
}
